# Generated by Django 5.0.1 on 2026-01-23 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('passport_number', models.CharField(max_length=50, unique=True)),
                ('jshir', models.CharField(blank=True, max_length=20, null=True)),
                ('citizenship', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(max_length=50)),
                ('course_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('major', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('Russian', 'Russian'), ('English', 'English'), ('Uzbek', 'Uzbek')], default='English', max_length=10)),
                ('visa_type', models.CharField(default='Student Visa', max_length=50)),
                ('visa_start_date', models.DateField(blank=True, null=True)),
                ('visa_end_date', models.DateField(blank=True, null=True)),
                ('registration_start_date', models.DateField(blank=True, null=True)),
                ('registration_end_date', models.DateField(blank=True, null=True)),
                ('registration_address_type', models.CharField(choices=[('Dormitory', 'Dormitory'), ('Other', 'Other')], default='Dormitory', max_length=20)),
                ('registration_address_details', models.TextField(blank=True, null=True)),
                ('tuition_total', models.DecimalField(decimal_places=2, default=2800.0, max_digits=10)),
                ('tuition_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('registration_fee_total', models.DecimalField(decimal_places=2, default=300.0, max_digits=10)),
                ('registration_fee_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dormitory_status', models.CharField(choices=[('None', 'None'), ('Normal', 'Normal'), ('VIP', 'VIP')], default='None', max_length=10)),
                ('dormitory_check_in_date', models.DateField(blank=True, null=True)),
                ('dormitory_planned_checkout_date', models.DateField(blank=True, null=True)),
                ('dormitory_actual_checkout_date', models.DateField(blank=True, null=True)),
                ('dormitory_monthly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dormitory_paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
