// Yo'nalishlar ro'yxati (kerak bo'lsa nomlarni almashtiring)
export const MAJORS = [
  'Buxgalteriya hisobi va audit',
  'Dasturiy injiniring',
  'Dori-darmonlar texnologiyasi',
  'Ekonomika',
  'Elektr energetikasi',
  'Filologiya (ingliz tili)',
  'Filologiya (rus tili)',
  'General Medicine',
  'Harbiy ta\'lim',
  'International Business',
  'International Law',
  'Kompyuter injiniringi',
  'Menejment',
  'Moliya',
  'Pedagogika va psixologiya',
  'Pharmacy',
  'Soliq va soliqqa tortish',
  'Tibbiyot',
  'Tijoriy bank ishi',
  'Xalqaro iqtisodiyot',
  'Yurisprudensiya',
].sort((a, b) => a.localeCompare(b));
